minimum_pre_commit_version: "2.7.1"
default_language_version:
  python: "python3.10"
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.0.1"
    hooks:
      - id: "check-toml"
        name: "Check TOML"
  - repo: "https://github.com/adrienverge/yamllint"
    rev: "v1.25.0"
    hooks:
      - id: "yamllint"
        name: "Check YAML"
        args: ["-c", ".yamllint.yaml"]
  - repo: "http://gitlab.com/pycqa/flake8"
    rev: "3.9.2"
    hooks:
      - id: "flake8"
        name: "Check python using flake8"
        args: ["--ignore=E501,W503"]
  - repo: "https://github.com/PyCQA/bandit"
    rev: "1.7.0"
    hooks:
      - id: "bandit"
        name: "Check python using bandit"
        files: "^(src)/"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v0.982"
    hooks:
      - id: "mypy"
        name: "Check python using mypy"
        additional_dependencies:
          - "types-requests"
  - repo: "https://github.com/timothycrosley/isort"
    rev: "5.9.3"
    hooks:
      - id: "isort"
        name: "Format python using isort"
  - repo: "https://github.com/psf/black"
    rev: "22.3.0"
    hooks:
      - id: "black"
        name: "Format python using black"
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.0.1"
    hooks:
      - id: "end-of-file-fixer"
        name: "Fix end of files"
      - id: "trailing-whitespace"
        name: "Fix trailing whitespace"
