#!/usr/bin/env python3.10
# pylint: disable=broad-except
# pylint: disable=invalid-name
# pylint: disable=missing-module-docstring
# pylint: disable=missing-function-docstring

import argparse
import sys
from argparse import Namespace

from lib import run  # type: ignore


def parse_args() -> Namespace:
    parser = argparse.ArgumentParser(
        prog="serve",
        description="Run a development server",
    )
    parser.add_argument("--host", action="store", dest="host", default="0.0.0.0")
    parser.add_argument("--port", action="store", dest="port", default="5000")
    return parser.parse_args()


def main(host: str, port: str) -> int:
    return run(
        "poetry",
        "run",
        "uvicorn",
        "slackbox.main:app",
        "--host",
        host,
        "--port",
        port,
        "--reload",
    )


if __name__ == "__main__":
    kwargs = parse_args()
    sys.exit(main(**kwargs.__dict__))
