name: "commits"
on: ["pull_request_target"]

jobs:
  lint-commit-messages:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Lint commits"
        uses: "actions-ecosystem/action-lint-commits@v1"
        id: "lint-commits"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          regex: "(fix|feat|refacto)\\((core|users|contributions)\\(: [a-z]+"
          format: "markdown"
      - name: "Remove labels after lint success"
        uses: "actions-ecosystem/action-remove-labels@v1"
        if: "${{ steps.lint-commits.outputs.unmatched_commits == '' }}"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "need changes"
      - name: "Comment pull request after lint failure"
        uses: "actions-ecosystem/action-create-comment@v1"
        if: "${{ steps.lint-commits.outputs.unmatched_commits != '' }}"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          body: |
            Please conform to the **lower cased** commit format:
            ```
            <type>(<scope>): <message>
            ```

            - __Allowed types:__

            | Types | Description |
            | :---- | :----------- |
            | feat | a new feature added to the application |
            | fix | a fix to an existing feature  |
            | refacto | a code refactoring without any changes to the application |

            - __Allowed scopes:__

            | Scopes | Description |
            | :----- | :----------- |
            | core      | anything that is code related (lint, CI/CD, developper experience, etc. ) |
            | user   | anything impacting the user domain |
            | contributions   | anything impacting the contribution domain |
      - name: "Add label after lint failure"
        uses: "actions-ecosystem/action-add-labels@v1"
        if: "${{ steps.lint-commits.outputs.unmatched_commits != '' }}"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "need changes"
      - name: "Force failure after lint failure"
        if: "${{ steps.lint-commits.outputs.unmatched_commits != '' }}"
        run: "exit 1"
