name: lint-codebase
on: [pull_request]
env:
  REGISTRY_HOSTNAME: ${{ secrets.REGISTRY_HOSTNAME }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-path: ~/.cache/virtualenvs/
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/virtualenvs/
          key: poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: make init
      - name: Lint codebase
        run: make lint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-path: ~/.cache/virtualenvs/
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/virtualenvs/
          key: poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: make init
      - name: Run unit tests and code coverage
        run: make tests-unit
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-path: ~/.cache/virtualenvs/
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs/
          key: poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: make init
      - name: Run integration tests and code coverage
        run: make tests-integration
