#!/bin/bash

MSG_FILE=$1
MSG_CONTENT="$(cat $MSG_FILE)"
SCRIPT_PATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
SCRIPT_DIR="$(dirname $SCRIPT_PATH)"

$SCRIPT_DIR/lint-commit --commit current --message "$MSG_CONTENT"
